// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title Groth16Verifier (Template)
 * @notice This is a TEMPLATE showing the expected interface.
 *         The actual verifier is generated by snarkjs after circuit compilation.
 *         Run: npm run setup:circuit
 *         Generated file: contracts/LTVVerifier.sol
 *
 * @dev Public signals for LTV circuit:
 *   [0] ltvResultBps    - Computed LTV in basis points
 *   [1] thresholdBps    - Threshold in basis points
 *   [2] positionIdHash  - Hash of position ID
 *   [3] timestamp       - Proof generation timestamp
 */

contract Groth16VerifierTemplate {
    // Verification key components (populated by snarkjs)
    // These are placeholder values - actual values come from trusted setup

    uint256 constant SNARK_SCALAR_FIELD = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /**
     * @notice Verify a Groth16 proof
     * @param _pA Proof element A (2 field elements)
     * @param _pB Proof element B (2x2 field elements)
     * @param _pC Proof element C (2 field elements)
     * @param _pubSignals Public inputs (4 for LTV circuit)
     * @return bool True if proof is valid
     */
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) public view returns (bool) {
        // This is a template - actual implementation is generated by snarkjs
        // The generated verifier includes:
        // 1. Pairing checks using bn128 precompiles
        // 2. Verification key encoding
        // 3. Public input processing

        // Placeholder - always reverts in template
        revert("Use generated LTVVerifier.sol");
    }
}
