// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title LTVOracle
 * @notice On-chain LTV verification using Groth16 proofs
 * @dev The actual Groth16Verifier contract is generated by snarkjs
 *      Run: npm run setup:circuit to generate contracts/LTVVerifier.sol
 */

interface IGroth16Verifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) external view returns (bool);
}

contract LTVOracle {
    // === State ===
    IGroth16Verifier public immutable verifier;
    address public owner;

    // Position ID hash => LTV data
    mapping(bytes32 => LTVRecord) public ltvRecords;

    // Authorized CRE workflow addresses
    mapping(address => bool) public authorizedSubmitters;

    struct LTVRecord {
        uint256 ltvBps;           // LTV in basis points
        uint256 thresholdBps;     // Threshold in basis points
        uint256 timestamp;        // When proof was submitted
        bool isBreached;          // Whether LTV >= threshold
        bool verified;            // Whether proof was valid
    }

    // === Events ===
    event LTVProofSubmitted(
        bytes32 indexed positionIdHash,
        uint256 ltvBps,
        uint256 thresholdBps,
        bool isBreached,
        uint256 timestamp
    );

    event LiquidationTriggered(
        bytes32 indexed positionIdHash,
        uint256 ltvBps,
        uint256 thresholdBps
    );

    // === Errors ===
    error Unauthorized();
    error InvalidProof();
    error StaleProof();

    // === Modifiers ===
    modifier onlyOwner() {
        if (msg.sender != owner) revert Unauthorized();
        _;
    }

    modifier onlyAuthorized() {
        if (!authorizedSubmitters[msg.sender]) revert Unauthorized();
        _;
    }

    // === Constructor ===
    constructor(address _verifier) {
        verifier = IGroth16Verifier(_verifier);
        owner = msg.sender;
        authorizedSubmitters[msg.sender] = true;
    }

    // === Admin Functions ===
    function setAuthorized(address submitter, bool authorized) external onlyOwner {
        authorizedSubmitters[submitter] = authorized;
    }

    function transferOwnership(address newOwner) external onlyOwner {
        owner = newOwner;
    }

    // === Core Functions ===

    /**
     * @notice Submit an LTV proof from CRE workflow
     * @param proof The Groth16 proof components
     * @param publicSignals [ltvBps, thresholdBps, positionIdHash, timestamp]
     */
    function submitLTVProof(
        uint[2] calldata pA,
        uint[2][2] calldata pB,
        uint[2] calldata pC,
        uint[4] calldata publicSignals
    ) external onlyAuthorized {
        // Verify the proof
        bool valid = verifier.verifyProof(pA, pB, pC, publicSignals);
        if (!valid) revert InvalidProof();

        // Extract public signals
        uint256 ltvBps = publicSignals[0];
        uint256 thresholdBps = publicSignals[1];
        bytes32 positionIdHash = bytes32(publicSignals[2]);
        uint256 timestamp = publicSignals[3];

        // Check freshness (proof must be recent)
        if (block.timestamp > timestamp + 5 minutes) revert StaleProof();

        // Determine if breached
        bool isBreached = ltvBps >= thresholdBps;

        // Store record
        ltvRecords[positionIdHash] = LTVRecord({
            ltvBps: ltvBps,
            thresholdBps: thresholdBps,
            timestamp: timestamp,
            isBreached: isBreached,
            verified: true
        });

        emit LTVProofSubmitted(
            positionIdHash,
            ltvBps,
            thresholdBps,
            isBreached,
            timestamp
        );

        // If breached, emit liquidation event
        if (isBreached) {
            emit LiquidationTriggered(positionIdHash, ltvBps, thresholdBps);
        }
    }

    /**
     * @notice Check if a position is breached
     * @param positionIdHash Hash of the position ID
     * @return isBreached Whether position LTV >= threshold
     * @return ltvBps Current LTV in basis points
     * @return lastUpdate Timestamp of last proof
     */
    function checkPosition(bytes32 positionIdHash)
        external
        view
        returns (bool isBreached, uint256 ltvBps, uint256 lastUpdate)
    {
        LTVRecord memory record = ltvRecords[positionIdHash];
        return (record.isBreached, record.ltvBps, record.timestamp);
    }

    /**
     * @notice Get full LTV record for a position
     */
    function getLTVRecord(bytes32 positionIdHash)
        external
        view
        returns (LTVRecord memory)
    {
        return ltvRecords[positionIdHash];
    }
}
