# CRE Workflow Settings for LTV Monitor

staging:
  user-workflow:
    workflow-name: "ltv-monitor-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"

production:
  user-workflow:
    workflow-name: "ltv-monitor-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
